### ISSUE TITLE
Add support for PacketEvents

### ISSUE THREAD

**Issue by NoltoxGit** [HibiscusMC/HibiscusCommons#4]
Hello,
Is it possible to add PacketEvents support instead of ProtocolLib?

There are already several other plugins that have added PacketEvents support, or even replaced ProtocolLib to use PacketEvents only.

For all the developers who have switched, this one is better, and the code is better maintained by the developer and the community. :)

## GitHub link: https://github.com/retrooper/packetevents

**Comment by LoJoSho** [comment]
We previously used PacketEvents, but continually ran into issues that made it annoying to work with even compared to ProtocolLib. Hence, why we now use ProtocolLib.
